"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {api} from "@/lib/api";
import {BaselineCard} from "./brief-baseline";
import "./brief.css";
type Question={key:string;label:string;hint:string;type:string;required:boolean;options:string[];unit:string;example:string;large:boolean};
type Section={key:string;title:string;description:string;questions:Question[]};
export type BriefRow={id:number;labels?:Record<string,string>;answers:Record<string,string>;preview:{knowledge:string;tone:string;goal:string;checklist:string[]}|null;status:string;source:string;project_id:number;workspace_id:number;lead_id:number|null;lead_project_id?:number;demo_workspace_id:number|null;created_at:string;ai_fields?:string[];transcript?:string};
const json=(body:unknown,method="POST")=>({method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body),timeoutMs:300000});
export default function BriefForm({projectId}:{projectId?:number}){
 const [sections,setSections]=useState<Section[]>([]),[answers,setAnswers]=useState<Record<string,string>>({}),[step,setStep]=useState(0),[row,setRow]=useState<BriefRow|null>(null);
 const [text,setText]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[saved,setSaved]=useState("");
 const rowId=useRef<number|null>(null),queue=useRef<Promise<unknown>>(Promise.resolve()),ready=useRef(false),revision=useRef(0);
 useEffect(()=>{ready.current=false;let alive=true;(async()=>{const s=await api<{sections:Section[]}>("/brief/questions");const rows=await api<BriefRow[]>(`/brief/projects/${projectId}`);const r=rows[0]||await api<BriefRow>(`/brief/projects/${projectId}`,json({answers:{}}));if(alive){setSections(s.sections);rowId.current=r.id;setRow(r);setAnswers(r.answers);ready.current=true;}})().catch(e=>setError(e.message));return()=>{alive=false;};},[projectId]);
 const persist=(snapshot:Record<string,string>)=>{const id=rowId.current;const rev=revision.current;setSaved("Сохраняем…");const job=queue.current.catch(()=>{}).then(async()=>{const r=await api<BriefRow>(`/brief/projects/${projectId}/${id}`,json({answers:snapshot},"PUT"));if(rev===revision.current){setRow(r);setSaved("Черновик сохранён");}return r;});queue.current=job;return job;};
 useEffect(()=>{if(!ready.current)return;const timer=setTimeout(()=>persist(answers).catch(e=>setError(e.message)),700);return()=>clearTimeout(timer);},[answers]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError("");try{await fn();}catch(e){setError(e instanceof Error?e.message:"Не удалось обработать бриф");}finally{setBusy(false);}};
 const change=(key:string,value:string)=>{revision.current++;setAnswers(a=>({...a,[key]:value}));setRow(r=>r?{...r,preview:null,status:"draft"}:r);};
 const importRow=(r:BriefRow)=>{revision.current++;rowId.current=r.id;setRow(r);setAnswers(r.answers);setStep(0);};
 const upload=(file:File,recording:boolean)=>run(async()=>{if(file.size>(recording?200:5)*1024*1024)throw new Error(recording?"Запись должна быть не больше 200 МБ":"Документ должен быть не больше 5 МБ");await queue.current.catch(()=>{});const f=new FormData();f.append("file",file);importRow(await api<BriefRow>(`/brief/projects/${projectId}/${recording?"recording":"upload"}`,{method:"POST",body:f,timeoutMs:1800000}));});
 const action=(kind:string)=>run(async()=>{await persist(answers);setRow(await api<BriefRow>(`/brief/projects/${projectId}/${rowId.current}/${kind}`,json({})));setSaved(kind==="apply"?"Знания применены к ИИ":kind==="confirm"?"Бриф подтверждён":"Предпросмотр готов");});
 const required=sections.flatMap(s=>s.questions).filter(q=>q.required),filled=required.filter(q=>answers[q.key]?.trim()).length;
 const current=sections[step],num=(k:string)=>Number((answers[k]||"").replace(/\s/g,"").replace(",","."))||0;
 const limit=num("econ.check")*num("econ.margin")/100*num("sales.conv")/100;
 return <main className="briefShell fullBriefShell"><Link href={`/settings?project_id=${projectId}`}>← В кабинет</Link><header className="briefTop"><strong>Бриф на запуск маркетинга</strong><span>{saved||"Черновик сохраняется автоматически"}</span></header><progress value={filled} max={required.length||1}/><p>Обязательные ответы: {filled} из {required.length} · {row?.status==="applied"?"Подтверждён":row?.status==="review"?"Проверьте ответы ИИ":"Черновик"}</p>{error&&<p role="alert" className="briefError">{error}</p>}
 <section><h2>Заполнить из записи встречи</h2><p>ИИ переносит только факты из разговора. Поля, для которых нет данных, останутся пустыми.</p><label>MP3, M4A, WAV или OGG, до 200 МБ<input disabled={busy} type="file" accept=".mp3,.m4a,.wav,.ogg" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f,true);}}/></label><label>Или вставьте расшифровку<textarea disabled={busy} value={text} maxLength={100000} onChange={e=>setText(e.target.value)}/></label><button disabled={busy||!text.trim()} onClick={()=>run(async()=>{await queue.current.catch(()=>{});importRow(await api<BriefRow>(`/brief/projects/${projectId}/text`,json({text})));})}>{busy?"Обрабатываем…":"Разложить по вопросам"}</button><details><summary>Загрузить готовый бриф</summary><input disabled={busy} type="file" accept=".docx,.pdf,.md,.txt" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f,false);}}/></details>{row?.transcript&&<details><summary>Исходная расшифровка</summary><pre>{row.transcript}</pre></details>}</section>
 <div className="briefLayout"><aside><nav className="briefRail">{sections.map((s,i)=><button key={s.key} disabled={busy} aria-current={i===step?"step":undefined} onClick={()=>setStep(i)}>{i+1}. {s.title} <small>{s.questions.filter(q=>answers[q.key]?.trim()).length}/{s.questions.length}</small></button>)}</nav><div className="briefHero"><small>Предел цены заявки</small><strong>{limit>0?"до "+Math.round(limit).toLocaleString("ru-RU")+" ₽":"—"}</strong><p>{limit>0?"Столько можно платить за одну заявку, чтобы реклама окупалась с первой продажи.":"Укажите средний чек, маржу и сколько заявок из 100 покупают — посчитаем, сколько можно платить за заявку без убытка."}</p></div></aside><section><h1>{current?.title}</h1><p>{current?.description}</p>{current?.questions.map(q=><div className="briefQuestion" key={q.key}><div><label htmlFor={q.key}>{q.label} {q.required&&<small className="briefBadge">обязательно</small>}</label><p>{q.hint}</p>{row?.ai_fields?.includes(q.key)&&answers[q.key]&&<small className="briefBadge">Заполнено ИИ, проверьте</small>}</div><div>{q.type==="one"||q.type==="many"?<div className="briefOptions">{q.options.map(v=>{const values=(answers[q.key]||"").split(", ");const selected=q.type==="many"?values.includes(v):answers[q.key]===v;return <button type="button" disabled={busy} key={v} aria-pressed={selected} onClick={()=>change(q.key,q.type==="many"?(selected?values.filter(x=>x!==v):[...values.filter(Boolean),v]).join(", "):selected?"":v)}>{v}</button>;})}</div>:q.type==="area"?<textarea id={q.key} disabled={busy} maxLength={10000} rows={q.large?7:4} placeholder={q.example?"Например: "+q.example:undefined} value={answers[q.key]||""} onChange={e=>change(q.key,e.target.value)}/>:<input id={q.key} disabled={busy} maxLength={10000} inputMode={q.type==="num"?"decimal":undefined} value={answers[q.key]||""} onChange={e=>change(q.key,e.target.value)}/>}<small>{q.unit}</small></div></div>)}<div className="briefActions"><button disabled={step===0||busy} onClick={()=>setStep(step-1)}>Назад</button><button disabled={step===sections.length-1||busy} onClick={()=>setStep(step+1)}>Дальше</button></div></section></div>
 <section><h2>Проверка и подтверждение</h2><p>Проверьте заполненные поля. Подтверждение брифа не меняет знания ИИ автоматически.</p><button disabled={busy||!Object.values(answers).some(Boolean)} onClick={()=>action("confirm")}>Подтвердить бриф</button><button disabled={busy||row?.status!=="applied"} onClick={()=>action("preview")}>Предпросмотр знаний ИИ</button>{row?.preview&&<><pre>{row.preview.knowledge}</pre><p>Тон: {row.preview.tone} · Цель: {row.preview.goal}</p><ul>{row.preview.checklist.map((v,i)=><li key={i}>{v}</li>)}</ul><button disabled={busy||row.status!=="applied"} onClick={()=>action("apply")}>Применить к ИИ</button></>}</section>
 {projectId&&<BaselineCard projectId={projectId}/>}
 </main>;
}
