"use client";
import {useEffect,useState} from "react";
import {api} from "@/lib/api";
import "./brief.css";
const fields:Record<string,string>={leads:"Заявок в месяц",cpl:"Цена заявки, ₽",conversion:"Конверсия в продажу, %",sales:"Продаж в месяц",average_check:"Средний чек, ₽",budget:"Бюджет, ₽",revenue:"Выручка, ₽"};
type Values=Record<string,number|string|boolean|null>;
type State={values:Values;can_edit:boolean;can_fix:boolean;history:{at:string;actor_id:number;admin:boolean;before:Values;after:Values}[]};
export function BaselineCard({projectId,current,period}:{projectId:number;current?:Record<string,number|null|undefined>;period?:string}){
 const [data,setData]=useState<State|null>(null),[values,setValues]=useState<Values>({}),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{api<State>(`/brief/projects/${projectId}/baseline`).then(r=>{setData(r);setValues(r.values);}).catch(e=>setError(e.message));},[projectId]);
 const save=async(fix=false)=>{setBusy(true);setError("");try{const payload=Object.fromEntries(Object.entries(values).filter(([k])=>k!=="fixed"));const r=await api<State>(`/brief/projects/${projectId}/baseline`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({values:payload,fix})});setData(r);setValues(r.values);}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить точку А");}finally{setBusy(false);}};
 const metric=String(values.goal_metric||"leads"),start=typeof values[metric]==="number"?values[metric] as number:null,goal=typeof values.goal_value==="number"?values.goal_value:null,now=current?.[metric];
 const progress=now!=null&&start!=null&&goal!=null&&goal!==start?(now-start)/(goal-start)*100:null;
 return <section className="briefBaseline"><h2>Точка А и цель</h2>{error&&<p role="alert" className="briefError">{error}</p>}{data&&<><p>{values.fixed?"Точка А зафиксирована. Изменения доступны только администратору.":"Укажите цифры на дату старта и цель на 3 месяца."}</p>{current&&<p>Текущие цифры — за {period||"выбранный период"}. Для сравнения месячных показателей выберите полный месяц.</p>}<div className="briefBaselineGrid">{Object.entries(fields).filter(([k])=>k!=="revenue").map(([k,label])=><label key={k}>{label}<input type="number" min="0" max={k==="conversion"?100:undefined} disabled={!data.can_edit||busy} value={values[k]==null?"":String(values[k])} onChange={e=>setValues({...values,[k]:e.target.value===""?null:Number(e.target.value)})}/>{current&&<small>Сейчас: {current[k]==null?"—":Number(current[k]).toLocaleString("ru-RU")} · Изменение: {current[k]!=null&&typeof values[k]==="number"?(Number(current[k])-Number(values[k])).toLocaleString("ru-RU"):"—"}</small>}</label>)}</div><label>Дата старта<input type="date" disabled={!data.can_edit||busy} value={String(values.start_date||"")} onChange={e=>setValues({...values,start_date:e.target.value})}/></label><label>Цель на 3 месяца<input type="number" min="0" disabled={!data.can_edit||busy} value={values.goal_value==null?"":String(values.goal_value)} onChange={e=>setValues({...values,goal_value:e.target.value===""?null:Number(e.target.value)})}/><select disabled={!data.can_edit||busy} value={metric} onChange={e=>setValues({...values,goal_metric:e.target.value})}>{Object.entries(fields).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Описание цели<textarea disabled={!data.can_edit||busy} value={String(values.goal_text||"")} onChange={e=>setValues({...values,goal_text:e.target.value})}/></label>{current&&<p>Прогресс к цели: {progress==null?"недостаточно данных":Math.round(progress)+"%"}{progress!=null&&<progress max={100} value={Math.max(0,Math.min(100,progress))}/>}</p>}{data.can_edit&&<div className="briefActions"><button disabled={busy} onClick={()=>save()}>Сохранить</button>{data.can_fix&&<button disabled={busy||!!values.fixed} onClick={()=>save(true)}>Зафиксировать</button>}</div>}<details><summary>История изменений ({data.history.length})</summary>{data.history.slice().reverse().map((h,i)=><div key={i}><p>{new Date(h.at).toLocaleString("ru-RU")} · {h.admin?"Администратор":"Владелец"}</p><pre>{JSON.stringify({до:h.before,после:h.after},null,2)}</pre></div>)}</details></>}</section>;
}
