"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {api} from "@/lib/api";
import "./express-quiz.css";
type Q={k:string;type:string;t:string;why?:string;f?:string[][];req?:string[];o?:string[];idk?:string;other?:string;extra?:{k:string;t:string;o:string[]}};
type A=Record<string,string|string[]|boolean>;
type Result={assessment_id:number;calculation:{limit_cpl:number|null;current_cpl:number|null;recommendations:string[][]};demo:{username:string;password:string;login_url:string}|null;expires_at:string|null};
const KEY="stl-express-v1";
const rub=(v:number)=>Math.round(v).toLocaleString("ru-RU")+" ₽";
export default function ExpressQuiz(){
 const [schema,setSchema]=useState<{questions:Q[];privacy_url:string;accepting:boolean}|null>(null),[a,setA]=useState<A>({}),[step,setStep]=useState(-1);
 const [consent,setConsent]=useState(false),[trap,setTrap]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<Result|null>(null),[ready,setReady]=useState(false);
 const [theme,setTheme]=useState<"light"|"dark">("light");
 useEffect(()=>{const saved=localStorage.getItem("stl-express-theme");setTheme(saved==="dark"||(!saved&&matchMedia("(prefers-color-scheme: dark)").matches)?"dark":"light");},[]);
 const attribution=useRef<{utm:Record<string,string>;referrer:string}>({utm:{},referrer:""});
 useEffect(()=>{try{const d=JSON.parse(localStorage.getItem(KEY)||"{}");setA(d.a||{});setStep(Math.max(-1,Math.min(11,d.c??-1)));}catch{}const utm:Record<string,string>={};new URLSearchParams(location.search).forEach((v,k)=>{if(k.startsWith("utm_"))utm[k]=v;});attribution.current={utm,referrer:document.referrer};setReady(true);api<typeof schema>("/brief/express").then(setSchema).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(ready&&!result)try{localStorage.setItem(KEY,JSON.stringify({a,c:step}));}catch{}},[a,step,ready,result]);
 const go=(s:number)=>{setStep(s);setError("");window.scrollTo({top:0,behavior:"smooth"});};
 const has=(v:unknown)=>Array.isArray(v)?!!v.length:typeof v==="string"&&!!v.trim();
 const q=schema?.questions[step];
 const valid=(q:Q,values:A)=>q.type==="fields"?(q.req||[]).every(k=>has(values[k])):q.type==="one"?has(values[q.k])&&(!q.extra||has(values[q.extra.k])):true;
 const choose=(key:string,value:string,many=false,auto=false)=>{const next={...a};if(many){const arr=Array.isArray(a[key])?a[key] as string[]:[];next[key]=arr.includes(value)?arr.filter(v=>v!==value):[...arr,value];}else next[key]=value;if(q?.idk)next[q.k+"_idk"]=false;setA(next);if(auto&&q&&valid(q,next))setTimeout(()=>go(step+1),220);};
 const options=(key:string,values:string[],many=false,auto=false)=><div className={q?.type==="scale"&&key===q.k?"scale":"opts"} role="group" aria-label={q?.t}>{values.map(v=><button className={"opt"+(many?"":" single")} type="button" key={v} aria-pressed={many?Array.isArray(a[key])&&a[key].includes(v):a[key]===v} onClick={()=>choose(key,v,many,auto)}><span className="mk" aria-hidden="true"/><span>{v}</span></button>)}</div>;
 const submit=async()=>{setBusy(true);setError("");try{const r=await api<Result>("/brief/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answers:a,consent,website:trap,...attribution.current}),timeoutMs:180000});setResult(r);localStorage.removeItem(KEY);}catch(e){setError(e instanceof Error?e.message:"Не удалось отправить оценку");}finally{setBusy(false);}};
 return <main className="expressPage" data-theme={theme}><div className="page"><header className="top"><strong className="brand">Step<span>To</span>Lead</strong><button className="theme" type="button" aria-pressed={theme==="dark"} onClick={()=>{const next=theme==="light"?"dark":"light";setTheme(next);localStorage.setItem("stl-express-theme",next);}}>{theme==="light"?"Тёмная тема":"Светлая тема"}</button><span>{result?"Ваш результат":step<0?"2 минуты":`Вопрос ${step+1} из 12`}</span></header><div className="bar" role="progressbar" aria-label="Прогресс оценки" aria-valuemin={0} aria-valuemax={12} aria-valuenow={result?12:Math.max(0,step)}><i className="fill" style={{width:`${(result?12:Math.max(0,step))/12*100}%`}}/></div>{error&&<p role="alert" className="error">{error}</p>}
 {!schema?<p>Загрузка…</p>:result?<section className="card anim"><div className="qh"><h1>{String(a.name)}, вот ваш результат</h1></div><div className="hero"><small>Предельная цена заявки</small><strong>{result.calculation.limit_cpl? "до "+rub(result.calculation.limit_cpl):"Нужны цифры"}</strong><p>{result.calculation.limit_cpl?`Расчёт: ${rub(Number(a.pay))} за клиента × ${a.conv==="6+"?6:a.conv} покупки из 10 заявок.`:"Для расчёта не хватает суммы, которую вы готовы отдать за клиента, или доли заявок, которые покупают. Менеджер поможет посчитать на звонке."}</p></div>
 {result.calculation.limit_cpl&&result.calculation.current_cpl?<div className="cmp"><h3>Ваша цена заявки и предел</h3><div className="track" role="img" aria-label={`Сейчас ${rub(result.calculation.current_cpl)}, предел ${rub(result.calculation.limit_cpl)}`}><i className="fill" style={{width:`${result.calculation.current_cpl/(Math.max(result.calculation.limit_cpl,result.calculation.current_cpl)*1.15)*100}%`,background:result.calculation.current_cpl>result.calculation.limit_cpl?"var(--warn)":"linear-gradient(90deg,var(--accent),var(--accent-2))"}}/><b className="lim" style={{left:`${result.calculation.limit_cpl/(Math.max(result.calculation.limit_cpl,result.calculation.current_cpl)*1.15)*100}%`}}/></div><div className="legend num"><span>Сейчас: <b>{rub(result.calculation.current_cpl)}</b></span><span>Предел (черта): <b>{rub(result.calculation.limit_cpl)}</b></span></div><p className={"verdict "+(result.calculation.current_cpl>result.calculation.limit_cpl?"warn":"ok")}>{result.calculation.current_cpl>result.calculation.limit_cpl?"Сейчас каждая заявка стоит дороже, чем вы можете себе позволить.":"Цена заявки в пределах нормы — есть запас для роста."}</p></div>:null}
 <div className="ins"><h3>Что поправить в первую очередь</h3><ul>{result.calculation.recommendations.map(([title,text])=><li key={title}><i/><div><b>{title}</b> {text}</div></li>)}</ul></div>{result.demo?<div className="out"><h3>Ваш демо-кабинет готов</h3><p>Сохраните доступ: пароль показывается только сейчас. Демо до {new Date(result.expires_at!).toLocaleDateString("ru-RU")}.</p><p>Логин: <strong>{result.demo.username}</strong></p><p>Пароль: <code>{result.demo.password}</code></p><Link className="btn pri" href={result.demo.login_url}>Открыть демо-кабинет</Link></div>:<div className="out"><h3>Демо-кабинет пришлёт менеджер</h3><p className="note">Заявка сохранена. Менеджер свяжется с вами и пришлёт доступ.</p></div>}</section>:step<0?<section className="card anim"><div className="qh"><h1>Сколько вы можете платить <span>за одну заявку?</span></h1><p>Ответьте на 12 коротких вопросов о вашем бизнесе. В конце покажем предельную цену заявки, при которой реклама окупается, и что стоит поправить в первую очередь.</p></div><div className="facts">{["2–3 минуты","Без регистрации","Результат сразу"].map(t=><span className="fact" key={t}>{t}</span>)}</div><div className="foot"><button className="btn pri" onClick={()=>go(0)}>{a.what?"Продолжить":"Начать"}</button><span className="note">Ответы сохраняются в вашем браузере</span></div></section>:q&&<section className="card anim" key={q.k}><div className="qh"><h1>{q.t}</h1>{q.why&&<p>{q.why}</p>}</div>
 {(q.type==="many"||q.type==="one"||q.type==="scale")&&options(q.k,q.o||[],q.type==="many",q.type!=="many"&&!q.extra)}
 {q.extra&&<><p>{q.extra.t}</p>{options(q.extra.k,q.extra.o)}</>}
 {q.other&&<textarea className="ta" aria-label={q.other} placeholder={q.other} value={String(a[q.k+"_other"]||"")} onChange={e=>setA({...a,[q.k+"_other"]:e.target.value})}/>}
 <div className={q.f?.length===2?"two":"fields"}>{q.f?.map(f=><div className="field" key={f[0]}><label htmlFor={"f-"+f[0]}>{f[1]}</label>{f[2]==="area"?<textarea className="ta" id={"f-"+f[0]} maxLength={2000} value={String(a[f[0]]||"")} placeholder={f[3]} onChange={e=>setA({...a,[f[0]]:e.target.value})}/>:<div className={f[2]==="num"?"unit":undefined}><input className="in" id={"f-"+f[0]} inputMode={f[2]==="num"?"decimal":undefined} maxLength={f[0]==="contact"?120:f[0]==="name"?180:2000} value={String(a[f[0]]||"")} placeholder={f[3]} onChange={e=>setA({...a,[f[0]]:e.target.value,...(q.idk?{[q.k+"_idk"]:false}:{})})}/>{f[4]&&<span>{f[4]}</span>}</div>}</div>)}</div>
 {q.idk&&<button className="idk" onClick={()=>{setA({...a,[q.k+"_idk"]:true,...(q.type==="scale"?{[q.k]:""}:{})});go(step+1);}}>{q.idk}</button>}
 {step===11&&<><div className="trap" aria-hidden="true"><input tabIndex={-1} autoComplete="off" value={trap} onChange={e=>setTrap(e.target.value)}/></div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Согласен на обработку персональных данных для связи и подготовки разбора согласно <a href={schema.privacy_url||undefined} target="_blank" rel="noreferrer">политике обработки персональных данных</a> (152-ФЗ).</label>{!schema.accepting&&<p className="error">Отправка пока не настроена. Ответы останутся в черновике.</p>}</>}
 <div className="foot"><button className="btn link" disabled={busy} onClick={()=>go(step-1)}>Назад</button><button className="btn pri" disabled={busy||!valid(q,a)||(step===11&&(!consent||!schema.accepting))} onClick={()=>step===11?submit():go(step+1)}>{busy?"Готовим кабинет…":step===11?"Показать результат":"Дальше"}</button></div></section>}
 </div></main>;
}
