"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { api, AdConnection } from "@/lib/api";

type CampaignRow = { connection_id:number; connection_name:string; platform:string; external_campaign_id:string; name:string; spend:number; impressions:number; clicks:number; applications:number; cpc:number|null; first_date:string|null; last_date:string|null; hypothesis_id:number|null };
type Hypothesis = { id:number; name:string; audience:string|null; offer:string|null; landing_url:string|null; status:string; spend:number; impressions:number; clicks:number; applications:number; cpc:number|null; conversion_rate:number|null; cost_per_application:number|null; campaigns:CampaignRow[] };
type Analysis = { workspace:{id:number;name:string}; connections:AdConnection[]; hypotheses:Hypothesis[]; applications:number; unattributed_applications:number; unassigned_campaigns:CampaignRow[] };

const money = (value:number) => new Intl.NumberFormat("ru-RU", {style:"currency",currency:"RUB",maximumFractionDigits:0}).format(value);
const number = (value:number) => new Intl.NumberFormat("ru-RU").format(value);

export default function ClientAdvertisingAnalysis() {
  const params=useParams<{workspaceId:string}>(); const workspaceId=Number(params.workspaceId);
  const [data,setData]=useState<Analysis|null>(null); const [open,setOpen]=useState<number|null>(null);
  const [modal,setModal]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  const [targets,setTargets]=useState<Record<string,string>>({});
  const load=useCallback(async()=>{try{setData(await api<Analysis>(`/marketing/workspaces/${workspaceId}/analysis`));setError("");}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить аналитику");}},[workspaceId]);
  useEffect(()=>{load();},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{await api("/marketing/hypotheses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workspace_id:workspaceId,name:form.get("name"),audience:form.get("audience")||null,offer:form.get("offer")||null,landing_url:form.get("landing_url")||null})});setModal(false);setNotice("Гипотеза создана.");await load();}catch(e){setError(e instanceof Error?e.message:"Не удалось создать гипотезу");}finally{setBusy(false);}}
  async function assign(campaign:CampaignRow){const hypothesisId=Number(targets[`${campaign.connection_id}:${campaign.external_campaign_id}`]);if(!hypothesisId)return;setBusy(true);try{await api(`/marketing/hypotheses/${hypothesisId}/campaigns`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({connection_id:campaign.connection_id,external_campaign_id:campaign.external_campaign_id})});setNotice("Кампания добавлена в гипотезу.");await load();}catch(e){setError(e instanceof Error?e.message:"Не удалось привязать кампанию");}finally{setBusy(false);}}
  if(!data)return <div className="page"><p className={error?"notice error":"portalMuted"}>{error||"Загружаем аналитику…"}</p></div>;
  const all=[...data.hypotheses.flatMap(x=>x.campaigns),...data.unassigned_campaigns]; const spend=all.reduce((s,x)=>s+x.spend,0); const clicks=all.reduce((s,x)=>s+x.clicks,0);
  return <div className="page hypothesisPage">
    <header className="topbar"><div className="crumbs"><Link href="/admin/advertising">Реклама</Link><b>/</b><strong>{data.workspace.name}</strong></div><span className="userAvatar">ЕД</span></header>
    <section className="pageHeader"><div><p className="eyebrow">Глубокая аналитика</p><h1>{data.workspace.name}</h1><p className="subtitle">Кабинеты → гипотезы → рекламные кампании</p></div><button className="button primary" onClick={()=>setModal(true)}>＋ Гипотеза</button></section>
    {error&&<p className="notice error">{error}</p>}{notice&&<p className="notice success">{notice}</p>}
    <section className="analysisTrail"><span>Компания</span><b>→</b><span>{data.connections.length} кабинетов</span><b>→</b><span>{data.hypotheses.length} гипотез</span><b>→</b><span>{all.length} кампаний</span></section>
    <section className="metricsGrid analysisMetrics"><article className="metricCard featured"><div className="metricTop"><span>Вложено</span><i>Все кампании</i></div><strong>{money(spend)}</strong></article><article className="metricCard"><div className="metricTop"><span>Клики</span><i>Трафик</i></div><strong>{number(clicks)}</strong></article><article className="metricCard"><div className="metricTop"><span>Заявки</span><i>CRM</i></div><strong>{number(data.applications)}</strong><p>{data.unattributed_applications} пока без гипотезы</p></article><article className="metricCard"><div className="metricTop"><span>Цена заявки</span><i>CPL</i></div><strong>{data.applications?money(spend/data.applications):"—"}</strong></article></section>
    <section className="hypothesisList"><div className="panelHead"><div><p className="eyebrow">Матрёшка</p><h2>Гипотезы</h2></div></div>
      {data.hypotheses.map(item=><article className={`hypothesisCard ${open===item.id?"open":""}`} key={item.id}><button className="hypothesisHead" onClick={()=>setOpen(open===item.id?null:item.id)}><div><span className={`hypothesisStatus ${item.status}`}>Тестируется</span><h3>{item.name}</h3><p>{item.audience||"Аудитория пока не описана"}</p></div><dl><div><dt>Вложено</dt><dd>{money(item.spend)}</dd></div><div><dt>Заявки</dt><dd>{number(item.applications)}</dd></div><div><dt>CPL</dt><dd>{item.cost_per_application?money(item.cost_per_application):"—"}</dd></div><div><dt>Конверсия</dt><dd>{item.conversion_rate==null?"—":`${item.conversion_rate.toFixed(2)}%`}</dd></div></dl><b>{open===item.id?"−":"＋"}</b></button>{open===item.id&&<div className="hypothesisBody"><div className="hypothesisBrief"><div><small>Оффер</small><p>{item.offer||"Не заполнен"}</p></div><div><small>Посадочная страница</small><p>{item.landing_url?<a href={item.landing_url} target="_blank">{item.landing_url}</a>:"Не указана"}</p></div></div><CampaignTable rows={item.campaigns}/></div>}</article>)}
      {!data.hypotheses.length&&<div className="empty"><span>◉</span><h3>Создайте первую гипотезу</h3><p>Опишите аудиторию и оффер, затем добавьте рекламные кампании.</p></div>}
    </section>
    <section className="panel unassignedPanel"><div className="panelHead"><div><p className="eyebrow">Требуют разбора</p><h2>Кампании без гипотезы</h2></div><span className="secureHint">{data.unassigned_campaigns.length}</span></div>{data.unassigned_campaigns.map(c=><div className="assignRow" key={`${c.connection_id}:${c.external_campaign_id}`}><div><strong>{c.name}</strong><small>{c.connection_name} · {money(c.spend)} · {number(c.clicks)} кликов</small></div><select value={targets[`${c.connection_id}:${c.external_campaign_id}`]||""} onChange={e=>setTargets({...targets,[`${c.connection_id}:${c.external_campaign_id}`]:e.target.value})}><option value="">Выберите гипотезу</option>{data.hypotheses.map(h=><option value={h.id} key={h.id}>{h.name}</option>)}</select><button disabled={busy} onClick={()=>assign(c)}>Добавить</button></div>)}{!data.unassigned_campaigns.length&&<p className="portalMuted">Все загруженные кампании распределены.</p>}</section>
    {modal&&<div className="modalBackdrop"><form className="modal" onSubmit={create}><div className="modalHead"><div><p className="eyebrow">Новый уровень аналитики</p><h2>Создать гипотезу</h2></div><button type="button" className="close" onClick={()=>setModal(false)}>×</button></div><label>Название<input name="name" required minLength={2} placeholder="Например, Владельцы интернет-магазинов" autoFocus/></label><label>Целевая аудитория<textarea name="audience" rows={3} placeholder="Кому показываем рекламу"/></label><label>Оффер<textarea name="offer" rows={3} placeholder="Что предлагаем и почему это выгодно"/></label><label>Посадочная страница<input name="landing_url" type="url" placeholder="https://..."/></label><button className="button primary full" disabled={busy}>{busy?"Создаём…":"Создать гипотезу"}</button></form></div>}
  </div>;
}

function CampaignTable({rows}:{rows:CampaignRow[]}){return <div className="campaignAnalysisTable">{rows.map(row=><article key={`${row.connection_id}:${row.external_campaign_id}`}><div><strong>{row.name}</strong><small>{row.connection_name} · ID {row.external_campaign_id}</small></div><span>{money(row.spend)}</span><span>{number(row.clicks)} кликов</span><span>{number(row.applications)} заявок</span></article>)}{!rows.length&&<p className="portalMuted">К этой гипотезе ещё не добавлены кампании.</p>}</div>}
