"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, TelegramAccount } from "@/lib/api";

type Task = { id:number; account_id:number; account_phone?:string; account_username?:string|null; sources:string[]; status:string; collected_count:number; processed_sources:number; total_limit:number; error?:string|null; created_at:string };
type Log = { id:number; level:string; message:string; created_at:string };
type Contact = { id:number; id_username:string; telegram_user_id:number; username:string|null; first_name:string|null; last_name:string|null; full_name:string; gender:string; bio:string|null; personal_channel:string|null; activity:string|null; last_seen_at:string|null; messages:string[]; message_count:number; source_type:string; source:string; source_name:string|null; found_via:string };
type Details = Task & { logs:Log[]; contacts:Contact[]; total_contacts:number };

const STATUS:Record<string,string> = {queued:"В очереди",running:"Собирается",completed:"Готово",partial:"Частично",failed:"Ошибка",cancel_requested:"Останавливается",cancelled:"Остановлено"};
export default function ParserPage(){
  const [accounts,setAccounts]=useState<TelegramAccount[]>([]); const [tasks,setTasks]=useState<Task[]>([]);
  const [selected,setSelected]=useState<number|null>(null); const [details,setDetails]=useState<Details|null>(null);
  const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({account_id:"",sources:"",collect_messages:true,collect_members:true,collect_comments:true,extended_profile:false,per_source_limit:100,total_limit:5000,activity_filter:"all",max_offline_days:""});
  const active=useMemo(()=>tasks.some(t=>["queued","running","cancel_requested"].includes(t.status)),[tasks]);
  async function load(){ try { const [a,t]=await Promise.all([api<TelegramAccount[]>("/telegram-accounts"),api<Task[]>("/telegram-parser/tasks")]); setAccounts(a); setTasks(t); if(!form.account_id&&a[0]) setForm(v=>({...v,account_id:String(a[0].id)})); } catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить данные");} }
  async function open(id:number){setSelected(id); try{setDetails(await api<Details>(`/telegram-parser/tasks/${id}`));}catch(e){setError(e instanceof Error?e.message:"Не удалось открыть задачу");}}
  useEffect(()=>{load();},[]);
  useEffect(()=>{const timer=setInterval(()=>{load(); if(selected) open(selected);},active?2500:8000); return()=>clearInterval(timer);},[active,selected]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const task=await api<Task>("/telegram-parser/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,account_id:Number(form.account_id),sources:form.sources.split(/\n/).map(s=>s.trim()).filter(Boolean),per_source_limit:Number(form.per_source_limit),total_limit:Number(form.total_limit),max_offline_days:form.max_offline_days?Number(form.max_offline_days):null})});await load();await open(task.id);}catch(e){setError(e instanceof Error?e.message:"Не удалось запустить сбор");}finally{setBusy(false);}}
  async function cancel(id:number){try{await api(`/telegram-parser/tasks/${id}/cancel`,{method:"POST"});await load();}catch(e){setError(e instanceof Error?e.message:"Не удалось остановить задачу");}}
  return <div className="page parserPage">
    <header className="pageHeader"><div><p className="eyebrow">Telegram-инструменты</p><h1>Сбор контактов</h1><p className="subtitle">Участники, авторы сообщений и комментариев из доступных аккаунту групп и каналов.</p></div><span className="parserSafety">Только доступные Telegram-данные</span></header>
    {error&&<p className="notice error">{error}<button onClick={()=>setError("")}>×</button></p>}
    <section className="panel parserForm"><div className="panelHead"><div><p className="eyebrow">Новая задача</p><h2>Настройте сбор</h2></div><span className="secureHint">до 50 источников за запуск</span></div>
      <form onSubmit={submit}>
        <div className="parserGrid"><label>Telegram-аккаунт<select required value={form.account_id} onChange={e=>setForm({...form,account_id:e.target.value})}><option value="">Выберите аккаунт</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.username?`@${a.username}`:a.phone} · {a.status}</option>)}</select></label><label>Общий лимит уникальных контактов<input type="number" min="1" max="10000" value={form.total_limit} onChange={e=>setForm({...form,total_limit:Number(e.target.value)})}/></label></div>
        <label className="parserWide">Ссылки на чаты и каналы — по одной в строке<textarea required rows={5} placeholder={"https://t.me/example_chat\n@example_channel"} value={form.sources} onChange={e=>setForm({...form,sources:e.target.value})}/></label>
        <div className="parserChecks"><label><input type="checkbox" checked={form.collect_messages} onChange={e=>setForm({...form,collect_messages:e.target.checked})}/><span><b>Авторы сообщений</b><small>Кто писал в чате</small></span></label><label><input type="checkbox" checked={form.collect_members} onChange={e=>setForm({...form,collect_members:e.target.checked})}/><span><b>Участники</b><small>Если список открыт</small></span></label><label><input type="checkbox" checked={form.collect_comments} onChange={e=>setForm({...form,collect_comments:e.target.checked})}/><span><b>Комментаторы</b><small>Под постами каналов</small></span></label><label><input type="checkbox" checked={form.extended_profile} onChange={e=>setForm({...form,extended_profile:e.target.checked})}/><span><b>Описание профиля</b><small>Медленнее, больше запросов</small></span></label></div>
        <div className="parserGrid three"><label>Глубина по источнику<input type="number" min="1" max="5000" value={form.per_source_limit} onChange={e=>setForm({...form,per_source_limit:Number(e.target.value)})}/><small>Сообщений или участников</small></label><label>Фильтр активности<select value={form.activity_filter} onChange={e=>setForm({...form,activity_filter:e.target.value})}><option value="all">Без фильтра</option><option value="online">Только онлайн</option><option value="recent">Недавно в сети</option></select></label><label>Не старше, дней<input type="number" min="1" max="3650" placeholder="Не ограничивать" value={form.max_offline_days} onChange={e=>setForm({...form,max_offline_days:e.target.value})}/></label></div>
        <div className="parserSubmit"><p>Телефон виден только тогда, когда сам Telegram открыл его этому аккаунту. Дубликаты автоматически удаляются.</p><button className="button primary" disabled={busy||!accounts.length}>{busy?"Добавляем…":"▶ Запустить сбор"}</button></div>
      </form>
    </section>
    <section className="parserWorkspace"><div className="panel parserTasks"><div className="panelHead"><div><p className="eyebrow">История</p><h2>Задачи</h2></div><span className="secureHint">{tasks.length}</span></div><div className="parserTaskList">{tasks.map(t=><article className={selected===t.id?"selected":""} key={t.id} onClick={()=>open(t.id)}><span className={`parserState ${t.status}`}/><div><strong>Задача #{t.id} · {t.account_username?`@${t.account_username}`:t.account_phone}</strong><small>{t.sources.length} источников · {new Date(t.created_at).toLocaleString("ru-RU")}</small>{t.error&&<em>{t.error}</em>}</div><b>{t.collected_count}</b><i>{STATUS[t.status]||t.status}</i>{["queued","running"].includes(t.status)&&<button onClick={e=>{e.stopPropagation();cancel(t.id)}}>Стоп</button>}</article>)}{!tasks.length&&<div className="parserEmpty">Запущенные задачи появятся здесь.</div>}</div></div>
      <div className="panel parserDetails">{details?<><div className="panelHead"><div><p className="eyebrow">Задача #{details.id}</p><h2>{details.total_contacts} контактов</h2></div><div className="parserExports"><a href={`/api/telegram-parser/tasks/${details.id}/export?format=csv`}>CSV</a><a href={`/api/telegram-parser/tasks/${details.id}/export?format=xlsx`}>Excel</a></div></div><div className="parserProgress"><i style={{width:`${Math.min(100,details.collected_count/details.total_limit*100)}%`}}/></div>
        <div className="parserResultTable">{details.contacts.length?<table><thead><tr><th>ID/USERNAME</th><th>ID</th><th>USERNAME</th><th>ИМЯ</th><th>ФАМИЛИЯ</th><th>ПОЛНОЕ ИМЯ</th><th>ПОЛ</th><th>БИОГРАФИЯ</th><th>ЛИЧНЫЙ КАНАЛ</th><th>СТАТУС ОНЛАЙН</th><th>ПОСЛЕДНИЙ РАЗ В СЕТИ</th><th>СООБЩЕНИЯ</th><th>КОЛ-ВО СООБЩЕНИЙ</th><th>ТИП ИСТОЧНИКА</th><th>ССЫЛКА НА ИСТОЧНИК</th><th>НАЗВАНИЕ ИСТОЧНИКА</th></tr></thead><tbody>{details.contacts.map(c=><tr key={c.id}><td><strong>{c.id_username}</strong></td><td>{c.telegram_user_id}</td><td>{c.username||"—"}</td><td>{c.first_name||"—"}</td><td>{c.last_name||"—"}</td><td>{c.full_name||"—"}</td><td>{c.gender}</td><td className="parserLong">{c.bio||"—"}</td><td>{c.personal_channel?<a href={c.personal_channel.startsWith("http")?c.personal_channel:undefined} target="_blank">{c.personal_channel}</a>:"—"}</td><td>{c.activity||"—"}</td><td>{c.last_seen_at?new Date(c.last_seen_at).toLocaleString("ru-RU"):"—"}</td><td className="parserLong">{c.messages.length?c.messages.join(" — "):"—"}</td><td>{c.message_count}</td><td>{c.source_type}</td><td><a href={c.source} target="_blank">{c.source}</a></td><td>{c.source_name||"—"}</td></tr>)}</tbody></table>:<div className="parserEmpty">Контакты ещё не собраны.</div>}</div>
        <h3 className="parserLogTitle">Журнал выполнения</h3><div className="parserLogs">{details.logs.map(l=><article key={l.id} className={l.level}><time>{new Date(l.created_at).toLocaleTimeString("ru-RU")}</time><span>{l.message}</span></article>)}</div></>:<div className="parserEmpty tall">Выберите задачу, чтобы увидеть контакты и подробный журнал.</div>}</div>
    </section>
  </div>;
}
