"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { api, PortalUser } from "@/lib/api";

type Dashboard = { user: PortalUser; marketing: { spend:number; impressions:number; clicks:number; applications:number; cpc:number|null; conversion_rate:number|null; cost_per_application:number|null; connections:number }; sales:{new_leads:number;in_progress:number;deals:number;overdue:number}; team_count:number; brief_progress:number };
const money = (value:number) => new Intl.NumberFormat("ru-RU", { style:"currency", currency:"RUB", maximumFractionDigits:0 }).format(value);
export default function PortalDashboard() {
  const [data,setData]=useState<Dashboard|null>(null); const [error,setError]=useState("");
  useEffect(()=>{api<Dashboard>("/portal/dashboard").then(setData).catch(e=>setError(e.message));},[]);
  if(error) return <main className="portalSurface"><p className="notice error">{error}</p></main>;
  if(!data) return <main className="portalSurface"><p>Загружаем кабинет…</p></main>;
  const manager=data.user.role==="sales_manager"; const head=data.user.role==="sales_head";
  return <div className="portalShell"><aside className="portalSidebar"><div className="portalBrand"><span>↗</span><b>StepToLead</b></div><div className="portalCompany"><small>Компания</small><strong>{data.user.workspace_name}</strong></div><nav><Link className="active" href="/portal">Общая картина</Link>{!manager&&<a>Маркетинг</a>}<Link href="/portal/crm">Продажи</Link><Link href="/portal/crm">{manager?"Мои лиды":"Воронка"}</Link>{!manager&&!head&&<a>Бриф и стратегия</a>}<a>Уведомления</a></nav><button onClick={async()=>{await api("/portal/auth/logout",{method:"POST"});location.assign("/portal/login");}}>Выйти</button></aside><main className="portalMain"><header><div><p>{data.user.role_name}</p><h1>{manager?"Моя рабочая очередь":`Добрый день, ${data.user.display_name.split(" ")[0]}`}</h1><span>{manager?"Новые обращения и задачи на сегодня.":"Всё важное о маркетинге и продажах компании."}</span></div><div className="portalUser">{data.user.display_name.slice(0,2).toUpperCase()}</div></header>
    {data.user.must_change_password&&<div className="portalAlert"><b>Временный пароль</b><span>Для безопасности смените его после первого входа. Форма смены пароля появится в настройках профиля.</span></div>}
    <section className="portalKpis">{manager?<><article><small>Новые лиды</small><strong>{data.sales.new_leads}</strong><span>ожидают первого контакта</span></article><article><small>В работе</small><strong>{data.sales.in_progress}</strong><span>активных диалогов</span></article><article><small>Просрочено</small><strong>{data.sales.overdue}</strong><span>задач требуют внимания</span></article><article><small>Сделки</small><strong>{data.sales.deals}</strong><span>за текущий месяц</span></article></>:<><article><small>Вложено</small><strong>{money(data.marketing.spend)}</strong><span>за всё доступное время</span></article><article><small>Кликов</small><strong>{data.marketing.clicks}</strong><span>цена клика {data.marketing.cpc == null ? "—" : money(data.marketing.cpc)}</span></article><article><small>Заявки</small><strong>{data.marketing.applications}</strong><span>реальные обращения из CRM</span></article><article><small>Цена заявки</small><strong>{data.marketing.cost_per_application == null ? "—" : money(data.marketing.cost_per_application)}</strong><span>конверсия {data.marketing.conversion_rate == null ? "—" : `${data.marketing.conversion_rate.toFixed(2)}%`}</span></article></>}</section>
    <section className="portalGrid"><article className="portalPanel"><div><p className="eyebrow">{manager?"Приоритет":"Маркетинг"}</p><h2>{manager?"Новые лиды появятся здесь":"Данные рекламных кабинетов"}</h2></div><div className="portalEmpty"><span>{manager?"01":"↗"}</span><h3>{manager?data.sales.new_leads?`${data.sales.new_leads} новых лидов ждут обработки`:"Очередь пока пуста":data.marketing.connections?`${data.marketing.connections} рекламных кабинетов подключено`:"Подключите рекламу через администратора"}</h3><p>{manager?"Откройте рабочую очередь, свяжитесь с клиентом и зафиксируйте результат.":"После синхронизации здесь появятся вложения, клики и показатели по реальным заявкам CRM."}</p>{manager&&<Link className="portalInlineButton" href="/portal/crm">Открыть мои лиды</Link>}</div></article><article className="portalPanel"><p className="eyebrow">Следующий шаг</p><h2>{manager?"Рабочая очередь":"Воронка продаж"}</h2><p className="portalMuted">{manager?"Все назначенные вам лиды, сроки и статусы собраны в одном месте.":"Контролируйте новые обращения, назначения и движение сделок."}</p><Link className="portalInlineButton" href="/portal/crm">{manager?"Перейти к лидам":"Открыть CRM"}</Link></article></section>
  </main></div>;
}
