from fastapi import APIRouter, Depends
from app.core.access import require_admin
from app.api.routes import access, growth

from app.api.routes import campaigns, leads, proxies, telegram_accounts, telegram_parser, marketing, portal, result, analytics, ads, team, settings, crm, website, tilda, telegram_bot, crm_pro, messaging, telephony, launch, push, documents, widget, care, amo_import
from app.api.routes import automation

internal_router = APIRouter(dependencies=[Depends(require_admin)])
internal_router.include_router(campaigns.router)
internal_router.include_router(leads.router)
internal_router.include_router(telegram_accounts.router)
internal_router.include_router(telegram_parser.router)
internal_router.include_router(proxies.router)
internal_router.include_router(automation.router)
internal_router.include_router(marketing.router)
api_router = APIRouter()
api_router.include_router(access.router)
api_router.include_router(growth.public_router)
api_router.include_router(growth.admin_router)
api_router.include_router(telegram_bot.router)
api_router.include_router(portal.auth_router)
api_router.include_router(portal.inbound_router)
api_router.include_router(portal.admin_router)
api_router.include_router(portal.portal_router)
api_router.include_router(result.router)
api_router.include_router(analytics.router)
api_router.include_router(ads.router)
api_router.include_router(team.router)
api_router.include_router(settings.router)
api_router.include_router(crm_pro.router)
api_router.include_router(messaging.router)
api_router.include_router(telephony.webhook_router)
api_router.include_router(telephony.router)
api_router.include_router(launch.router)
api_router.include_router(launch.admin_router)
api_router.include_router(push.router)
api_router.include_router(documents.router)
api_router.include_router(care.router)
api_router.include_router(amo_import.router)
api_router.include_router(documents.public_router)
api_router.include_router(crm.router)
api_router.include_router(widget.router)
api_router.include_router(website.router)
api_router.include_router(tilda.router)
api_router.include_router(internal_router)
