"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { api } from "@/lib/api";
import { base, message, post } from "../../leadgen/shared";
import styles from "../../leadgen/leadgen.module.css";
import type { Sequence } from "./types";
type Result={enrolled:number;skipped:number;results:{company_id:number;ok:boolean;reason_text?:string;reason?:string}[]};
export default function EnrollDialog({ids,close,completed}:{ids:number[];close:()=>void;completed:()=>void}){
  const [sequences,setSequences]=useState<Sequence[]>([]),[selected,setSelected]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[result,setResult]=useState<Result|null>(null);
  const ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow="hidden";ref.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){e.preventDefault();close();}if(e.key!=="Tab")return;const nodes=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not([disabled]),select,a[href]')||[]).filter(node=>node.getClientRects().length);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first?.focus();}};document.addEventListener("keydown",key);return()=>{document.body.style.overflow=overflow;document.removeEventListener("keydown",key);previous?.focus();};},[close]);
  useEffect(()=>{const controller=new AbortController();api<{items:Sequence[]}>(`${base}/sequences`,{signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setSequences(data.items);}).catch(e=>{if(!controller.signal.aborted)setError(message(e));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[]);
  async function enroll(){if(!selected||busy)return;setBusy(true);setError("");try{const data=await post<Result>(`/sequences/${selected}/enroll`,{company_ids:ids});setResult(data);completed();}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <><button type="button" className={styles.overlay} aria-label="Закрыть запуск цепочки" tabIndex={-1} onClick={close}/><div ref={ref} className={`${styles.card} ${styles.modal}`} role="dialog" aria-modal="true" aria-labelledby="enroll-title" tabIndex={-1}><h2 id="enroll-title">Запустить цепочку</h2>{error&&<div role="alert" className={styles.error}>{error}{/Добавьте.*ящик/i.test(error)&&<p><Link href="/admin/outreach/email?tab=mailboxes">Добавить ящик →</Link></p>}</div>}{loading?<p role="status">Загружаем цепочки…</p>:result?<div role="status" className={styles.notice}>Зачислено {result.enrolled}. Пропущено {result.skipped}.{result.results.filter(item=>!item.ok).map(item=><p key={item.company_id}>Компания #{item.company_id}: {item.reason_text||item.reason||"Причина не указана"}</p>)}</div>:<><p className={styles.muted}>Выбрано компаний: {ids.length}. После запуска касания выполняются по расписанию цепочки.</p><label className={styles.field}>Цепочка<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Выберите цепочку</option>{sequences.map(sequence=><option key={sequence.id} value={sequence.id} disabled={!sequence.is_active}>{sequence.name}{!sequence.is_active?" · Выключена":""}</option>)}</select></label>{!sequences.length&&<p><Link href="/admin/outreach/email?tab=sequences">Создать цепочку →</Link></p>}</>}<div className={styles.actions}>{!result&&<button type="button" className={styles.primary} disabled={loading||busy||!selected} onClick={enroll}>{busy?"Запускаем…":"Запустить"}</button>}<button type="button" className={styles.secondary} onClick={close}>{result?"Закрыть":"Отмена"}</button></div></div></>;
}
